In [60]:
import bs4 as bs
import urllib
import pandas as pd

In [61]:
years = [2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
results={}

In [62]:
for year in years:
    source = urllib.request.urlopen('https://www.iplt20.com/stats/'+str(year)).read()
    soup = bs.BeautifulSoup(source,'html')
    
    # title of the page
    print(year,':',soup.title.string)
    
    # title of the page
    points_table = soup.find_all(class_="standings-table__optional")
    data_dump=[]
    for entry in points_table:
        data_dump.append(entry.text)
    data_dump=data_dump[6:]
    
    # title of the page
    results_data=[]
    idx=0
    while idx<len(data_dump):
        data = [data_dump[idx],data_dump[idx+1],data_dump[idx+2],data_dump[idx+3]]
        data = list(map(int,data))
        results_data.append(data)
        idx+=8
        
    year_results={}
    teams = soup.find_all(class_="standings-table__team-name js-team")
    for standing,team in enumerate(teams):
        year_results[team.text]=results_data[standing],standing+1
    
    results[year]=year_results

2008 : IPLT20.com - Indian Premier League Official Website - Stats
2009 : IPLT20.com - Indian Premier League Official Website - Stats
2010 : IPLT20.com - Indian Premier League Official Website - Stats
2011 : IPLT20.com - Indian Premier League Official Website - Stats
2012 : IPLT20.com - Indian Premier League Official Website - Stats
2013 : IPLT20.com - Indian Premier League Official Website - Stats
2014 : IPLT20.com - Indian Premier League Official Website - Stats
2015 : IPLT20.com - Indian Premier League Official Website - Stats
2016 : IPLT20.com - Indian Premier League Official Website - Stats
2017 : IPLT20.com - Indian Premier League Official Website - Stats
2018 : IPLT20.com - Indian Premier League Official Website - Stats
2019 : IPLT20.com - Indian Premier League Official Website - Stats

In [63]:
results = pd.DataFrame(results)

In [74]:
df=pd.read_excel('AuctionData.xlsx')  
df.Team=df.Team.astype(str).str.strip()
df = df.set_index(['year', 'Team'])
df

                                        Balance  Overseas  TotalPlayers
year Team
2020 Chennai Super Kings             ₹15,00,000         8            24
     Delhi Capitals                ₹9,00,00,000         8            22
     Kings XI Punjab              ₹16,50,00,000         8            25
     Kolkata Knight Riders         ₹8,50,00,000         8            23
     Mumbai Indians                ₹1,95,00,000         8            24
     Rajasthan Royals             ₹14,75,00,000         8            25
     Royal Challengers Bangalore   ₹6,40,00,000         8            21
     Sunrisers Hyderabad          ₹10,10,00,000         8            25
2019 Chennai Super Kings           ₹3,20,00,000         8            25
     Delhi Capitals                ₹7,70,00,000         8            25
     Kings XI Punjab               ₹3,70,00,000         8            23
     Kolkata Knight Riders         ₹6,05,00,000         8            21
     Mumbai Indians                ₹3,55,00,000         8            24
     Rajasthan Royals              ₹7,15,00,000         8            25
     Royal Challengers Bangalore   ₹1,80,00,000         8            24
     Sunrisers Hyderabad           ₹5,30,00,000         8            23
2018 Chennai Super Kings           ₹6,50,00,000         8            25
     Delhi Capitals                ₹1,60,00,000         8            25
     Kings XI Punjab                 ₹10,00,000         7            21
     Kolkata Knight Riders                   ₹0         7            19
     Mumbai Indians                  ₹65,00,000         8            25
     Rajasthan Royals              ₹1,65,00,000         8            23
     Royal Challengers Bangalore     ₹15,00,000         8            24
     Sunrisers Hyderabad             ₹65,00,000         8            25
2017 Delhi Capitals                ₹9,05,00,000         9            26
     Gujarat Lions                ₹10,50,00,000         8            27
     Kings XI Punjab              ₹13,90,00,000         9            27
     Kolkata Knight Riders         ₹5,40,00,000         9            23
     Mumbai Indians                ₹3,35,50,000         9            27
     Rising Pune Supergiant          ₹30,00,000         8            26
...                                         ...       ...           ...
2016 Kolkata Knight Riders        ₹12,25,00,000         9            22
     Mumbai Indians                ₹1,30,50,000         8            26
     Rising Pune Supergiant        ₹5,20,00,000         7            23
     Royal Challengers Bangalore   ₹6,17,50,000         9            25
     Sunrisers Hyderabad           ₹8,40,00,000         7            25
2015 Chennai Super Kings             ₹70,00,000         9            25
     Delhi Capitals                ₹1,35,00,000         9            25
     Kings XI Punjab               ₹9,20,00,000         7            22
     Kolkata Knight Riders         ₹9,20,00,000         9            23
     Mumbai Indians                ₹4,90,50,000         9            26
     Rajasthan Royals             ₹10,65,00,000         8            25
     Royal Challengers Bangalore   ₹2,00,00,000         9            26
     Sunrisers Hyderabad           ₹9,35,00,000         8            23
2014 Chennai Super Kings             ₹20,00,000         8            20
     Delhi Capitals                          ₹0         7            23
     Kings XI Punjab               ₹4,10,00,000         7            23
     Kolkata Knight Riders         ₹1,00,00,000         8            21
     Mumbai Indians                   ₹5,00,000         8            21
     Rajasthan Royals              ₹5,55,00,000         8            25
     Royal Challengers Bangalore             ₹0         7            21
     Sunrisers Hyderabad           ₹1,00,00,000         7            24
2013 Chennai Super Kings             ₹1,846,087        11            22
     Delhi Capitals                    ₹655,978        11            26
     Kings XI Punjab                 ₹6,072,826         8            23
     Kolkata Knight Riders           ₹1,508,696        11            23
     Mumbai Indians                    ₹341,739        11            28
     Pune Warriors India               ₹804,130        11            33
     Rajasthan Royals                ₹7,071,304        10            21
     Royal Challengers Bangalore       ₹711,522        10            31
     Sunrisers Hyderabad             ₹5,583,696        11            26

[65 rows x 3 columns]

In [65]:
exchange_rate=61 #1USD=61INR, ~2013
inr_years=list(range(2014,2021))

In [76]:
df.Balance=df.Balance.str.replace(',','').str.replace('₹','').astype(float) #Remove rupee symbol
df.Balance[2013]=df.Balance[2013]*exchange_rate
df.Overseas=df.Overseas.astype(int)
df.TotalPlayers=df.TotalPlayers.astype(int)
finances = df

/Users/abm/.3-VirtualEnvironments/python3_ML/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [77]:
finances

                                      Balance  Overseas  TotalPlayers
year Team
2020 Chennai Super Kings            1500000.0         8            24
     Delhi Capitals                90000000.0         8            22
     Kings XI Punjab              165000000.0         8            25
     Kolkata Knight Riders         85000000.0         8            23
     Mumbai Indians                19500000.0         8            24
     Rajasthan Royals             147500000.0         8            25
     Royal Challengers Bangalore   64000000.0         8            21
     Sunrisers Hyderabad          101000000.0         8            25
2019 Chennai Super Kings           32000000.0         8            25
     Delhi Capitals                77000000.0         8            25
     Kings XI Punjab               37000000.0         8            23
     Kolkata Knight Riders         60500000.0         8            21
     Mumbai Indians                35500000.0         8            24
     Rajasthan Royals              71500000.0         8            25
     Royal Challengers Bangalore   18000000.0         8            24
     Sunrisers Hyderabad           53000000.0         8            23
2018 Chennai Super Kings           65000000.0         8            25
     Delhi Capitals                16000000.0         8            25
     Kings XI Punjab                1000000.0         7            21
     Kolkata Knight Riders                0.0         7            19
     Mumbai Indians                 6500000.0         8            25
     Rajasthan Royals              16500000.0         8            23
     Royal Challengers Bangalore    1500000.0         8            24
     Sunrisers Hyderabad            6500000.0         8            25
2017 Delhi Capitals                90500000.0         9            26
     Gujarat Lions                105000000.0         8            27
     Kings XI Punjab              139000000.0         9            27
     Kolkata Knight Riders         54000000.0         9            23
     Mumbai Indians                33550000.0         9            27
     Rising Pune Supergiant         3000000.0         8            26
...                                       ...       ...           ...
2016 Kolkata Knight Riders        122500000.0         9            22
     Mumbai Indians                13050000.0         8            26
     Rising Pune Supergiant        52000000.0         7            23
     Royal Challengers Bangalore   61750000.0         9            25
     Sunrisers Hyderabad           84000000.0         7            25
2015 Chennai Super Kings            7000000.0         9            25
     Delhi Capitals                13500000.0         9            25
     Kings XI Punjab               92000000.0         7            22
     Kolkata Knight Riders         92000000.0         9            23
     Mumbai Indians                49050000.0         9            26
     Rajasthan Royals             106500000.0         8            25
     Royal Challengers Bangalore   20000000.0         9            26
     Sunrisers Hyderabad           93500000.0         8            23
2014 Chennai Super Kings            2000000.0         8            20
     Delhi Capitals                       0.0         7            23
     Kings XI Punjab               41000000.0         7            23
     Kolkata Knight Riders         10000000.0         8            21
     Mumbai Indians                  500000.0         8            21
     Rajasthan Royals              55500000.0         8            25
     Royal Challengers Bangalore          0.0         7            21
     Sunrisers Hyderabad           10000000.0         7            24
2013 Chennai Super Kings          112611307.0        11            22
     Delhi Capitals                40014658.0        11            26
     Kings XI Punjab              370442386.0         8            23
     Kolkata Knight Riders         92030456.0        11            23
     Mumbai Indians                20846079.0        11            28
     Pune Warriors India           49051930.0        11            33
     Rajasthan Royals             431349544.0        10            21
     Royal Challengers Bangalore   43402842.0        10            31
     Sunrisers Hyderabad          340605456.0        11            26

[65 rows x 3 columns]

In [78]:
#Export
finances.to_pickle('IPL_finances.pkl')
results.to_pickle('IPL_results.pkl')